### ISSUE TITLE
Backtrace during CSV import

### ISSUE THREAD

**Issue by arvedarved** [mend-toolkit/import-sbom#8]
```
[2023-03-13 13:29:45]  INFO [main:536] Generating update request
[2023-03-13 13:29:45] ERROR [main:550] Failed to create update request file: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/arved/.local/bin/import_sbom", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/arved/.local/lib/python3.11/site-packages/mend_import_sbom/import_sbom.py", line 551, in main
    raise err
  File "/home/arved/.local/lib/python3.11/site-packages/mend_import_sbom/import_sbom.py", line 543, in main
    output_json = create_body(args)
                  ^^^^^^^^^^^^^^^^^
  File "/home/arved/.local/lib/python3.11/site-packages/mend_import_sbom/import_sbom.py", line 263, in create_body
    for rel_ in sbom["relationships"]:
                ~~~~^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```
PyCharm complains about the same issue (and other similar issues), see attached Screenshot
![mend](https://user-images.githubusercontent.com/6360709/224950082-7ba8d527-ce57-4f5c-aa17-acc5661ab828.png)

**Comment by tidharm** [comment]
@arvedarved, same as issue #9, we've added this fix and will release a new version shortly.

**Comment by clindseyws** [comment]
Upon review this request has been completed and merged.  Closing.

**Comment by arvedarved** [comment]
I am not sure how this is completed, there hasn't been any release since March.

**Comment by clindseyws** [comment]
I was just made aware that the build was never pushed, I am working with the resource to make sure that it does. Thank you for your patience.

**Comment by clindseyws** [comment]
Just noticed that I hadn't followed up on this thread, this issue was merged into Main and released August 10th.
