### ISSUE TITLE
[BUG] [import-sbom] Backtrace during Error handling:

### ISSUE THREAD

**Issue by arvedarved** [mend-toolkit/import-sbom#9]
Once I comment out the faulty code from #8 I run into the next error:

```
[2023-03-14 10:07:23]  INFO 
=========================
Mend SBOM Importer 23.3.1
=========================
[2023-03-14 10:07:23]  INFO [main:536] Generating update request
[2023-03-14 10:07:23]  INFO [create_body:330] Mend library search: adduser_3.118_all.deb-3.118
[2023-03-14 10:07:23] ERROR [main:550] Failed to create update request file: substring not found
Traceback (most recent call last):
  File "/home/arved/.local/lib/python3.11/site-packages/mend_import_sbom/import_sbom.py", line 219, in search_lib_by_name
    lib_lst = web.WS.call_ws_api(self=args.ws_conn, request_type="getBasicLibraryInfo",
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arved/.local/lib/python3.11/site-packages/ws_sdk/app.py", line 254, in call_ws_api
    __handle_ws_server_errors(resp.text)
  File "/home/arved/.local/lib/python3.11/site-packages/ws_sdk/app.py", line 218, in __handle_ws_server_errors
    raise WsSdkServerInsufficientPermissions(body['userKey'])
ws_sdk.ws_errors.WsSdkServerInsufficientPermissions: User token: '[REMOVED]' has insufficient permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arved/.local/bin/import_sbom", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/arved/.local/lib/python3.11/site-packages/mend_import_sbom/import_sbom.py", line 551, in main
    raise err
  File "/home/arved/.local/lib/python3.11/site-packages/mend_import_sbom/import_sbom.py", line 543, in main
    output_json = create_body(args)
                  ^^^^^^^^^^^^^^^^^
  File "/home/arved/.local/lib/python3.11/site-packages/mend_import_sbom/import_sbom.py", line 331, in create_body
    sha1_, lname_, err_, err_msg_ = search_lib_by_name(lib_name=pkg_name, lib_ver=pkg_ver, lib_type=key)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arved/.local/lib/python3.11/site-packages/mend_import_sbom/import_sbom.py", line 227, in search_lib_by_name
    error_code = json.loads(err.message[err.message.index("Error:")+6:])["errorCode"]  # Getting result as string, need to parse it
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: substring not found
```

It looks like the Error handler expects errors to begin with the string "Error: ", but the WS SDK does not format the Error like that

**Comment by tidharm** [comment]
@arvedarved I truly apologize for the delayed response; we've received this feedback from other sources as well, and have fixed it in the upcoming version, along with additional (non-breaking) changes we wanted to add.

We will release this version shortly.

**Comment by clindseyws** [comment]
Upon review this request has been completed and merged.  Closing.

**Comment by arvedarved** [comment]
I am not sure how this is completed, there hasn't been any release since March.

**Comment by clindseyws** [comment]
I was just made aware that the build was never pushed, I am working with the resource to make sure that it does.  Thank you for your patience.

**Comment by clindseyws** [comment]
Just noticed that I hadn't followed up on this thread, this issue was merged into Main and released August 10th.
